# Zomato Sales Data Analysis for different restaurent

##### Below we have given a two dimention numpy array where each row represneting a sales data for different restaurent
##### sales_data=np.array([
 ##### [1,150000,180000,220000,250000],
 ##### [2,120000,140000,160000,190000],
 ##### [3,200000,230000,260000,300000],
 ##### [4,180000,210000,240000,270000],
 ##### [5,160000,185000,205000,230000]
##### ])
##### exqmple:
##### row1:karim rastaurent
##### row2:dominos
##### row3:KFC
##### row4:aslam chicken
##### row5:javed nahari
##### and each row data storting the restaurent id,2021,22,23 and 24 sales

In [2]:
# question1:print the given array with the  message as:sales data for  different restaurent

import numpy as np
sales_data =np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])
print(f"sales data for different resturent: \n {sales_data}")

sales data for different resturent: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]


In [1]:
#  ques2:print the shape,size and diemntion of given numpy array

import numpy as np

sales_data = np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])

print(f"shape:{sales_data.shape}")
print(f"size:{sales_data.size}")
print(f"dimemsion:{sales_data.ndim}")

shape:(5, 5)
size:25
dimemsion:2


In [3]:
# ques3: print the  first three rows 

import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])

print(sales_data[:3,:5])



[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
# ques4: print given numpy array with all rows  except the restaurent id coulumn 

import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])

print(sales_data[:,1:])

[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [1]:
#ques5:  print given numpy array with first three rows  and all coulmn except  the restaurent id coulumn 

import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])

print(sales_data[0:3,1:5])

[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]]


In [2]:
#ques6: find the  total sales per year      

import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000], 
     [2,120000,140000,160000,190000], 
     [3,200000,230000,260000,300000], 
     [4,180000,210000,240000,270000],  
     [5,160000,185000,205000,230000]  
])

required_array=sales_data[:,1:]
total_sales_per_year=np.sum(required_array,axis=0)
print(total_sales_per_year)

[ 810000  945000 1085000 1240000]


In [3]:
# quest7: calculate the  total sales per restaurent 

import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000], #karim
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])


required_array=sales_data[0:,1:]

total_sales_per_res=np.sum(required_array,axis=1)
print(total_sales_per_res)

[800000 610000 990000 900000 780000]


In [4]:
# ques8 :calculate the min and max sales per restaurent 
import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000],  #150000
     [2,120000,140000,160000,190000],  # 120000
     [3,200000,230000,260000,300000],  #200000
     [4,180000,210000,240000,270000],  #150000
     [5,160000,185000,205000,230000]   #160000

])

required_array=sales_data[:,1:]
min_sales_per_res=np.min(required_array,axis=1) #[15k,120k,2lakh,150k,160k]
print(min_sales_per_res)

[150000 120000 200000 180000 160000]


In [ ]:
#ques8: calculate the max sales per year
import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])
print("max sales per year", sales_data)

In [8]:
#ques9: avg sales per restaurent 

import numpy as np

sales_data=np.array([
     [1,150000,180000,220000,250000],
     [2,120000,140000,160000,190000],
     [3,200000,230000,260000,300000],
     [4,180000,210000,240000,270000],
     [5,160000,185000,205000,230000]
])


required_array=sales_data[:,1:]
avg_sales_per_restaurent=np.mean(required_array,axis=1)
print(avg_sales_per_restaurent) 

[200000. 152500. 247500. 225000. 195000.]
